steps:
  - name: node:11
    entrypoint: yarn
    dir: 'pizza-authenticator'
  - name: node:11
    entrypoint: yarn
    args: ['package']
    dir: 'pizza-authenticator'
  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy', '-q']
    dir: 'pizza-authenticator/dist'  
