
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/make', '.']
    - name: 'gcr.io/$PROJECT_ID/make'
      args: ['-v']

images:
    - 'gcr.io/$PROJECT_ID/make'